Repository open-mmlab/mmclassification, pull requests merged in 2021-11, with the labels that each got.

#511 [Docs] Use docs link of other projects and add MMCV docs.
  docs/conf.py
  docs/index.rst
  docs/tutorials/config.md
  docs_zh-CN/conf.py
  docs_zh-CN/index.rst
Labels: Documentation

#506 [Refactor] Refactor `Resize` transform and add `Pad` transform.
  mmcls/datasets/pipelines/__init__.py
  mmcls/datasets/pipelines/transforms.py
  tests/test_data/test_pipelines/test_transform.py
Labels: Community discussion, Reproduction, Refactoring

#543 [Docs] Add mmflow and mim in banner and readme
  README.md
  README_zh-CN.md
  docs/conf.py
  docs_zh-CN/conf.py
Labels: Documentation

#542 fix bug when using iterbaserunner with 'val' workflow
  mmcls/models/classifiers/base.py
  tests/test_models/test_classifiers.py
Labels: Bug

#544 [Refactor] Remove useless `import_modules_from_string`.
  tools/analysis_tools/eval_metric.py
  tools/misc/print_config.py
  tools/visualizations/vis_pipeline.py
Labels: Refactoring
