Repository open-mmlab/mmclassification, pull requests merged in 2021-09, with the labels that each got.

#429 [Docs] Fix the version of sphinx
  requirements/docs.txt
Labels: Documentation

#428 [Docs] Add `CITATION.cff`
  CITATION.cff
  setup.py
Labels: Documentation

#437 [Enhance] Support setting `--out-items` in `tools/test.py`.
  tools/analysis_tools/analyze_results.py
  tools/analysis_tools/eval_metric.py
  tools/test.py
Labels: Enhancement

#435 [Docs] Update metafile and Readme
  configs/fp16/README.md
  configs/fp16/metafile.yml
  configs/mobilenet_v2/metafile.yml
  configs/resnet/README.md
  configs/resnet/metafile.yml
  configs/resnext/README.md
  configs/resnext/metafile.yml
  configs/seresnet/metafile.yml
  configs/shufflenet_v1/metafile.yml
  configs/shufflenet_v2/metafile.yml
  configs/swin_transformer/metafile.yml
  configs/tnt/README.md
  configs/tnt/metafile.yml
  configs/vgg/README.md
  configs/vgg/metafile.yml
  docs/model_zoo.md
  model-index.yml
Labels: Documentation

#436 [Refactor] Fix TnT compatibility and verbose warning.
  mmcls/models/backbones/tnt.py
  mmcls/models/classifiers/image.py
  tests/test_models/test_backbones/test_tnt.py
Labels: Refactoring

#457 [Docs] Use PyTorch style docs theme
  docs/_static/css/readthedocs.css
  docs/_static/image/mmcls-logo.png
  docs/api.rst
  docs/changelog.md
  docs/conf.py
  docs/index.rst
  docs/install.md
  docs/switch_language.md
  docs_zh-CN/_static/css/readthedocs.css
  docs_zh-CN/_static/image/mmcls-logo.png
  docs_zh-CN/api.rst
  docs_zh-CN/conf.py
  docs_zh-CN/index.rst
  docs_zh-CN/install.md
  docs_zh-CN/switch_language.md
  requirements/docs.txt
  setup.cfg
Labels: Documentation

#458 [Fix] Fix num_classes bug in pytorch2onnx.py
  tools/deployment/pytorch2onnx.py
Labels: Bug:P2

#466 [Docs] Update `getting_started.md` and `install.md` and rewrite `finetune.md`
  README.md
  README_zh-CN.md
  configs/fp16/metafile.yml
  docs/_static/css/readthedocs.css
  docs/community/CONTRIBUTING.md
  docs/conf.py
  docs/getting_started.md
  docs/index.rst
  docs/install.md
  docs/tutorials/finetune.md
  docs_zh-CN/_static/css/readthedocs.css
  docs_zh-CN/community/CONTRIBUTING.md
  docs_zh-CN/conf.py
  docs_zh-CN/getting_started.md
  docs_zh-CN/index.rst
  docs_zh-CN/install.md
  docs_zh-CN/model_zoo.md
  docs_zh-CN/tutorials/finetune.md
Labels: Documentation

#441 [Fix] Fix format error in `test.py` when metric returns `np.ndarray`
  tools/test.py
Labels: Bug:P2

#432 [Refactor] Use context manager to reuse matplotlib figures.
  docs_zh-CN/tutorials/MMClassification_python_cn.ipynb
  mmcls/core/visualization/__init__.py
  mmcls/core/visualization/image.py
  tests/test_utils/test_visualization.py
Labels: Refactoring
